- quant.ew/files/src/nickname.lua
- quant.ew/files/src/player_fns.lua
Add something to differentiate between players
> Early nicknames for players

- noita-proxy/src/bookkeeping/noita_launcher.rs
finds proton path to run noita automatically on linux
> auto detect "start game" parameters for linux

- noita-proxy/src/bookkeeping/noita_launcher.rs
- noita-proxy/src/lib.rs
should make it consistent with normal steam experience
> use steam linux runtime when available

- noita-proxy/Cargo.lock
- noita-proxy/Cargo.toml
- noita-proxy/src/lib.rs
> remove world sync version option, update packages

- quant.ew/files/system/notplayer_ai/notplayer_ai.lua
i couldn't find how you determined when wall is in the way so here is the basic implementation
> have notplayer target better with more then 2 players

- noita-proxy/assets/lang/zh-CN/main.ftl
- noita-proxy/src/util/lang.rs
My friends and I have always been concerned about how to connect to noita online. Yesterday, I saw this repository in a column on Bilibili and found that it did not have a Chinese interface, so I submitted this PR. This is my first time submitting a PR for another project on GitHub. If you have any questions, please let me know and I would greatly appreciate it.
> Add Chinese language support(zh-CN)

- noita-proxy/assets/lang/zh-CN/main.ftl
- noita-proxy/src/lib.rs
I have added a Chinese font, hoping to solve the problem of some text turning into blocks。
Since I don't know rust and my computer is Windows, I can't build a project on my computer to test if I've solved this problem.
> Fixed the issue with the Chinese font library

- noita-proxy/assets/lang/zh-CN/main.ftl
- noita-proxy/src/lib.rs
Since the 0.26.2 version update, the Chinese font has become very strange. I have replaced it with another Chinese font, hoping to solve this problem
> Try fixing the font

- noita-proxy/assets/lang/en-US/main.ftl
- noita-proxy/assets/lang/ru-RU/main.ftl
- noita-proxy/src/lib.rs
- noita-proxy/src/net.rs
- quant.ew/files/system/player_sync.lua
Addresses this issue: https://github.com/IntQuant/noita_entangled_worlds/issues/228
I had same problem too in the past, so i though it would be great to have this option just in case.
> add option to disable other players' cursors

- .github/workflows/release.yml
Reverts IntQuant/noita_entangled_worlds#255
> Revert "Add apt caching to release workflow"

- quant.ew/files/system/text/text.lua
simple and a lil buggy history for sent messages. features messages history itself, half implemented support for really long messages (85+ symbols) and not implemented storage of 100 messages (now you can only see 15 but all 100 is stored somewhere on your pc)
> chat history feature

- quant.ew/files/core/ctx.lua
- quant.ew/files/system/spectate/spectate.lua
- quant.ew/files/system/text/text.lua
- quant.ew/settings.lua
mainly colors and scroll features but also some code improvements and fixes
> a lot of chat improvenets

- noita-proxy/src/lib.rs
- noita-proxy/src/util/args.rs
Allows to fully skip any config from the "before first launch" state and go straight to proxy menu
80 commits behind, i take no responsibility if it breaks something lol
> Language cli arg

- noita-proxy/assets/lang/de-DE/main.ftl
- noita-proxy/src/util/lang.rs
Added a german translation (de-DE) to the assets and the language array of the proxy.
I tried to validate that most translations fit the context.
> Added German Translation

- quant.ew/files/system/text/text.lua
> chat line lenght are limited based on pixels not symbols, words are wrapping to the next line now, maybe some other fixes i dont remember already

- quant.ew/files/system/text/text.lua
for now ctrl+c and ctrl+v isnt implemented
> arrows, ctrl+arrows, home, end implementation to chat

- noita-proxy/assets/lang/ko-KR/main.ftl
First version of Korean translation.
> Rough Korean translation

- noita-proxy/src/lib.rs
New update had Korean language option, but the characters were all boxes so I added Korean font.
Since I don't have any programming experience, I looked at other language's commits and copied them.
Let's hope this works and doesn't break anything,
> Added Korean font, applied Korean font

- noita-proxy/assets/lang/ko-KR/main.ftl
Now that I can see translations on the app, there were a few parts that needed changes.
> Minor translation changes

- noita-proxy/assets/lang/fr-FR/main.ftl
Hey, loving the mod, me and my friends have been having a blast (litteraly) playing it. But some of them have a hard time with English so I thought I'd propose a French translation. This is my first time submitting something on Github so if I made any mistake or if you want me to do some modification please tell me ^^
> Add French language support(fr-FR)

- noita-proxy/src/lib.rs
> Fixed blackline in players list

- noita-proxy/assets/lang/ru-RU/main.ftl
> translated more strings for russian
